FROM node:20
 
ENV TZ="Asia/Ulaanbaatar"
 
WORKDIR /app
 
RUN apt-get update && apt-get install -y procps
 
RUN rm -rf node_modules/
 
COPY . .
 
RUN npm install
 
RUN npm run build
 
# RUN chgrp -R 0 /app && chmod -R g+rwX /app
 
# USER 1001
 
EXPOSE 3000
 
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
 
CMD npm run $NODE_ENV
