FROM node:20-slim
 
WORKDIR /app
 
COPY . .
 
ARG CI_COMMIT_SHA
ENV CI_COMMIT_SHA=$CI_COMMIT_SHA
 
RUN ls
RUN rm -rf node_modules/
RUN rm -rf .next/
RUN npm cache clean --force
RUN ls
 
# CMD export -p
 
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
 
RUN npm install --force
 
RUN npm run $NODE_ENV
 
RUN chgrp -R 0 /app && chmod -R g+rwX /app
 
USER 1001
 
EXPOSE 3000
 
CMD npm run start
